server:
  port: 9997
spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.40.131:29092
      group-id: customer-group
      
      
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties: 
         spring: 
         json :
              trusted: packages=*
        
   